spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user
      grid-fs-database: images
#  redis:
#    database: 0
#    host: localhost
#    password: 123456
#    port: 6379
  redis:
    sentinel:
      master: bkjkredis
      nodes: 172.29.10.50:16377,172.29.10.70:16377,172.29.10.201:16377
    timeout: 6000
    database: 16
server:
  port: 8888